// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVD8-NqIf2OAbxKIf0_IV3MSakU-22VHs',
    appId: '1:611701966388:web:2ad155fdf4df0324a3ac61',
    messagingSenderId: '611701966388',
    projectId: 'mynotes-pluswhale',
    authDomain: 'mynotes-pluswhale.firebaseapp.com',
    storageBucket: 'mynotes-pluswhale.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQqLDCy9307fA_TPvtYij5Ohfvp6Ad4m0',
    appId: '1:611701966388:android:17896823985b1fcea3ac61',
    messagingSenderId: '611701966388',
    projectId: 'mynotes-pluswhale',
    storageBucket: 'mynotes-pluswhale.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU2NeJdgvza_L0xgWHmZaxGemX5K20btg',
    appId: '1:611701966388:ios:40fcec8ddf74d830a3ac61',
    messagingSenderId: '611701966388',
    projectId: 'mynotes-pluswhale',
    storageBucket: 'mynotes-pluswhale.appspot.com',
    iosClientId: '611701966388-b9c52t9vu9r7jmheomvsi1immr3rfjhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU2NeJdgvza_L0xgWHmZaxGemX5K20btg',
    appId: '1:611701966388:ios:40fcec8ddf74d830a3ac61',
    messagingSenderId: '611701966388',
    projectId: 'mynotes-pluswhale',
    storageBucket: 'mynotes-pluswhale.appspot.com',
    iosClientId: '611701966388-b9c52t9vu9r7jmheomvsi1immr3rfjhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningflutter',
  );
}
